WhatDoYouSing/WhatDoYouSing-Front

src/components/PostPage/PostContent.jsx
src/components/RecordedPage/Bookmarked.jsx
src/components/RecordedPage/BookmarkedEmotion.jsx
src/components/RecordedPage/BookmarkedLyric.jsx
src/components/RecordedPage/Saved.jsx
src/components/common/LyricsItem.jsx

<br/>
내가남긴 추가 완료
<br/>
<br/>
<br/>

[Feature] 내가남긴 추가 완료

---

src/components/RecCarousel.jsx
src/components/common/LyricsItem.jsx
src/components/common/MainPage/SearchSection.jsx
src/index.css
src/pages/RecommendPage.jsx

<br/>
별 건 아니고 react-slick 라이브러리 사용해서 세로 캐러셀 반영했습니다!
pull 받아서 확인해보고 혹시 불편하거나 기획 의도처럼 움직이지 않는다면 바로 알려주세용,, 그럼 바로 자체 캐러셀 제작 들어갑니다🥲
그리고 메인 페이지에 스타일 수정사항 소소하게 반영했습니다!!
<br/>
<br/>
공용 컴포넌트 다룬 것은 아니라 큰 부분은 아니지만 pull 받았을 때 문제 없는지 확인해주면 고맙겠습니다.. 🥹 해피 2024입니다용
<br/>

4주차 개발 마무리 + 세로 캐러셀 반영

---

src/App.js
src/components/CommentBox.jsx
src/components/DeletePostModal.jsx
src/components/DetailPage/Comments.jsx
src/components/DetailPage/MeatballSelect.jsx
src/components/PostPage/PostContent.jsx
src/components/ResultPage/FilterResult.jsx
src/components/ResultPage/ResultTopbar.jsx
src/components/TopTab.jsx
src/components/common/EmotionList.jsx
src/pages/Detailpage.jsx
src/pages/Postpage.jsx
src/pages/ResultPage.jsx

퍼블리싱 마무리+글자수, 유효성검사+댓글등록+모달시도
<br/>
-/result 로 나오는 페이지로, 감정드래그부분은 detail에서 구현완료 후 0번째만 제외하여 렌더링 할 예정
-공백 제외한 글자수 카운팅 로직, 모든 칸 입력+감정칩 선택해야 버튼 활성화되는 유효성검사 로직 추가
-댓글 작성하여 제출(화살표)버튼 클릭 시 댓글컴포넌트가 아래쪽에 렌더링
-시도했으나 이중 컴포넌트 간의 값 전달로 인한 실패,, 아래서 상세히 설명예정
<br/>
<br/>
컴포넌트 구조는 이렇습니다: Detailpage.jsx > TopTab.jsx > MeatballSelect.jsx
탑탭에 있는 미트볼 클릭시 미트볼 드롭다운인 MeatballSelect.jsx 가 아래쪽에 뜨고, 거기서 삭제 또는 신고를 클릭 시 Detailpage.jsx에서 전체화면 대상으로 모달이 가운데에 뜨도록 하려고 시도해봤습니다.
참고한 자료는 https://cocoon1787.tistory.com/841 
와 같은 식으로 자식에서 부모 컴포넌트로 값 전달하도록 해보았는데 이중이라 그런지 변수도 굉장히 복잡하고 현재는 아예 화면 자체에 뜨지 않는 상태가 되어버려서 .. 싹 지우는것도 좋을 것 같습니다.. 🥲
사실 그냥 모달 띄우는건 괜찮겠는데 저 .. 자식의 자식 컴포넌트인게 문제인지라.. 아마도 삭제로 해서 성공하면 신고 모달도 바로 만들면 될 것 같습니다.
<br/>
회색 가로선을 border-bottom과 width 100%로 줬는데도 안 먹어서 혹시 방법이 있을지,, ((저번에 비슷하게 얘기했는데 이 방법이 아닌가..?? 헷갈리네요ㅠ …

[Feature] 퍼블리싱 마무리+글자수, 유효성검사+댓글등록+모달시도

---

public/index.html

index.html 업데이트
<br/>
<br/>
<br/>
<br/>

index.html 업데이트

---

package-lock.json
package.json
src/App.js
src/components/DetailPage/ShareModal.jsx
src/components/ImgSavePage/ImgCard.jsx
src/components/TopTab.jsx
src/images/close.svg
src/images/download.svg
src/images/save.svg
src/pages/Detailpage.jsx
src/pages/ImgSavePage.jsx

이미지 저장 구현 
Detailpage -> 공유버튼 -> 공유모달 -> 이미지로 저장하기 버튼 -> 이미지 생성창 -> 다운로드 버튼클릭 -> 빈 새 창에 이미지 띄움
<br/>
<br/>
pages에 ImgSavePage.jsx 추가하였습니다. 상단 TopBar 별도로 만들고 불러오는 ImgCard 컴포넌트가 캡쳐대상입니다. 이미지 카드에 들어갈 내용도 나중에 디테일페이지랑 동일하게 넘겨지도록 같이 (리코일로..?) 관리하게 될 것 같습니다.
<br/>
`npm install html2canvas` 라이브러리 사용하였습니다~~
css 줄바꿈 깨짐은 흔한 현상같은데,,, 해결책들 다 적용해봐도 바뀌지 않아 오전에 운영진에게 문의드릴 예정입니다 . .ㅜ
<br/>

[Feature] 이미지 저장 구현

---

src/apis/http.js
src/apis/user.js
src/assets/data/EmotionData.js
src/assets/data/UserProfileData.js
src/assets/recoil/recoil.js
src/components/IntroTopbar.jsx
src/components/Login-SignupPage/CheckModal.jsx
src/components/ResultPage/ResultTopbar.jsx
src/components/common/EmotionList.jsx
src/components/common/MainPage/Topbar.jsx
src/images/icons/cherry-prof-filled.svg
src/images/icons/cherry-prof.svg
src/images/icons/doong-ee-prof-filled.svg
src/images/icons/doong-ee-prof.svg
src/images/icons/henry-prof-filled.svg
src/images/icons/henry-prof.svg
src/images/icons/luke-prof-filled.svg
src/images/icons/luke-prof.svg
src/pages/MyPage.jsx
src/pages/RecordedPage.jsx
src/pages/UserInfo/LoginPage.jsx
src/pages/UserInfo/ProfileSettingPage.jsx
src/pages/UserInfo/SignupPage.jsx
src/pages/UserInfo/UserModifyIntroPage.jsx

API 연결 시작했습니다!
자체 로그인, 중복확인, 회원가입 및 마이페이지 로그인 토큰 관련 라우팅 처리했습니다.
<br/>
<br/>
<br/>
<br/>

로그인, 회원가입 API 연결

---

package-lock.json
package.json
src/App.js
src/apis/comment.js
src/apis/detail.js
src/components/CommentBox.jsx
src/components/DetailPage/Comments.jsx
src/components/DetailPage/GotoSong.jsx
src/components/DetailPage/LyricWithWriter.jsx
src/components/Reply.jsx
src/pages/Detailpage.jsx
src/setupProxy.js

댓글 답댓글 api 연결중

---

src/apis/http.js
src/apis/user.js
src/assets/recoil/apiRecoil.js
src/components/IntroTopbar.jsx
src/components/Login-SignupPage/CheckModal.jsx
src/components/common/DropDownBox.jsx
src/components/common/LyricsItem.jsx
src/components/common/MainPage/ChartSection.jsx
src/components/common/MainPage/LikeCarousel.jsx
src/components/common/MainPage/LikeSection.jsx
src/components/common/MainPage/Topbar.jsx
src/pages/Mainpage.jsx
src/pages/MyPage.jsx
src/pages/UserInfo/InitialPage.jsx
src/pages/UserInfo/LoginPage.jsx
src/pages/UserInfo/NicModifyPage.jsx
src/pages/UserInfo/PasModifyPage.jsx
src/pages/UserInfo/SignupPage.jsx
src/pages/UserInfo/UserDeletePage.jsx

자체 로그인 / 회원 가입 + 홈 좋아요 캐러셀 구현
<br/>
<br/>
<br/>
request URL 에 /를 유의하도록 합시다...^^
<br/>

자체 로그인 / 회원 가입 + 홈 좋아요 캐러셀 구현

---

package-lock.json
src/apis/detail.js
src/components/CommentBox.jsx
src/components/DetailPage/Comments.jsx
src/components/Reply.jsx
src/pages/Detailpage.jsx
src/setupProxy.js

가사 상세 조회, 댓글 조회 완료

---

src/apis/archieve.js
src/apis/comment.js
src/apis/lyrics.js
src/assets/recoil/recoil.js
src/components/CommentBox.jsx
src/components/DeletePostModal.jsx
src/components/DetailPage/Comments.jsx
src/components/PostPage/PostContent.jsx
src/components/Reply.jsx
src/components/TopTab.jsx
src/pages/Detailpage.jsx

api 연결: 댓글, 답댓글, 북마크, 글삭제
(api 명세서에 업데이트하였습니다)
<br/>
<br/>
<br/>
연결작업 외 추가로 할 작업은
-댓글에서 프로필 받아오기 (본인-->프론트작업/남-->백엔드 답변 주시면 작업시작)
-댓글에서 본인이 쓴 글만 삭제하기 보이도록 (프론트처리)
-게시글 delete 본인확인 로직 추가 (프론트처리)
-(연결을 다 해서 띄워보니 발견된....) 댓글쪽 css 손보기 ......
<br/>

api 연결: 댓글, 답댓글, 북마크, 글삭제

---

src/apis/my.js
src/apis/search.js
src/apis/user.js
src/assets/recoil/apiRecoil.js
src/components/IntroTopbar.jsx
src/components/RecordedPage/BookmarkedEmotion.jsx
src/components/RecordedPage/Saved.jsx
src/components/ResultPage/EmotionSearch.jsx
src/components/ResultPage/FilterResult.jsx
src/components/ResultPage/ResultTopbar.jsx
src/components/common/DropDownSearch.jsx
src/components/common/EmotionList.jsx
src/components/common/MainPage/LikeSection.jsx
src/components/common/MainPage/SearchSection.jsx
src/components/common/MainPage/Topbar.jsx
src/components/common/ResultLyrics.jsx
src/pages/Mainpage.jsx
src/pages/MyPage.jsx
src/pages/RecommendPage.jsx
src/pages/ResultPage.jsx
src/pages/SearchPage.jsx
src/pages/UserInfo/UserModifyIntroPage.jsx
src/statics/styles/GlobalStyle.js

MYPG / SURF API 연결
<br/>
<br/>
<br/>
<br/>

MYPG / SURF API 연결

---

src/apis/comment.js
src/apis/detail.js
src/apis/lyrics.js
src/assets/recoil/apiRecoil.js
src/components/CommentBox.jsx
src/components/DetailPage/Comments.jsx
src/components/DetailPage/EmotionBox.jsx
src/components/DetailPage/GotoSong.jsx
src/components/DetailPage/LyricWithWriter.jsx
src/components/DetailPage/ShareModal.jsx
src/components/ImgSavePage/ImgCard.jsx
src/components/IntroTopbar.jsx
src/components/PostPage/PostContent.jsx
src/components/Reply.jsx
src/components/TopTab.jsx
src/pages/Detailpage.jsx
src/pages/ImgSavePage.jsx
src/pages/Postpage.jsx

COMM, UPLO api 연결

---

src/App.js
src/apis/http.js
src/apis/user.js
src/components/CommentBox.jsx
src/components/DetailPage/EmotionBox.jsx
src/components/IntroTopbar.jsx
src/components/Login-SignupPage/CheckModal.jsx
src/components/RecCarousel.jsx
src/components/TopTab.jsx
src/components/common/MainPage/ChartSection.jsx
src/components/common/MainPage/SearchSection.jsx
src/components/common/RecLyrics.jsx
src/pages/UserInfo/InitialPage.jsx
src/pages/UserInfo/KakaoLoginPage.jsx
src/pages/UserInfo/KakaoNicknamePage.jsx
src/pages/UserInfo/KakaoProfilePage.jsx
src/pages/UserInfo/UserDeletePage.jsx

카카오 로그인 + https 연결 + 캐러셀 설정 변경

---

src/components/DetailPage/GotoSong.jsx
src/components/IntroTopbar.jsx
src/components/TopTab.jsx
src/pages/MyPage.jsx
src/pages/UserInfo/KakaoNicknamePage.jsx
src/pages/UserInfo/UserModifyIntroPage.jsx

[chore] 소소한 오류 수정

---

src/components/ImgSavePage/ImgCard.jsx
src/components/Pagination.jsx
src/components/PostPage/PostContent.jsx
src/components/RecordedPage/Saved.jsx
src/components/ResultPage/EmotionSearch.jsx
src/components/ResultPage/ResultTopbar.jsx
src/components/TopTab.jsx
src/components/common/Footer.jsx
src/components/common/MainPage/Topbar.jsx
src/pages/Detailpage.jsx
src/pages/Mainpage.jsx
src/pages/MyPage.jsx
src/pages/Postpage.jsx
src/pages/RecommendPage.jsx
src/pages/ResultPage.jsx
src/pages/SearchPage.jsx
src/pages/UserInfo/InitialPage.jsx
src/pages/UserInfo/KakaoDeletePage.jsx
src/pages/UserInfo/KakaoNicknamePage.jsx
src/pages/UserInfo/LoginPage.jsx
src/pages/UserInfo/NicModifyPage.jsx
src/pages/UserInfo/PasModifyPage.jsx
src/pages/UserInfo/ProfileSettingPage.jsx
src/pages/UserInfo/SignupPage.jsx
src/pages/UserInfo/UserDeletePage.jsx
src/pages/UserInfo/UserModifyIntroPage.jsx

- 페이지 바닥에 margin 주기 ✔️
- Topbar 선 생기는 거 고치기 ✔️
- 인풋 필드 동그래지고 겉 테두리 생기는 이슈 + 글자 크기 작아지는 이슈 수정 ✔️
- 페이지 들어갔을 때 맨 상단부터 뜨게 하기 ( 홈, 게시글 작성, 가사 상세, 마이 ) ✔️
- 이미지 저장에 인스타 아이디 추가 ✔️
<br/>
<br/>
<br/>
<br/>

[feat] 배포 이후 QA 반영

---

src/components/DetailPage/MeatballSelect.jsx
src/components/RecordedPage/Bookmarked.jsx
src/components/RecordedPage/BookmarkedEmotion.jsx
src/components/ResultPage/EmotionSearch.jsx
src/components/ResultPage/ResultTopbar.jsx
src/components/common/EmotionChip.jsx
src/pages/ImgSavePage.jsx
src/pages/RecommendPage.jsx
src/pages/RecordedPage.jsx
src/pages/UserInfo/LoginPage.jsx
src/pages/UserInfo/UserDeletePage.jsx

[feat] 5:43 QA

---

src/components/RecordedPage/Bookmarked.jsx
src/components/ResultPage/EmotionSearch.jsx
src/components/common/EmotionChip.jsx
src/pages/ImgSavePage.jsx
src/pages/UserInfo/UserDeletePage.jsx

기디 언니들과 함께 하는 베타버전 찐.막. QA
<br/>
<br/>
<br/>
<br/>

[feat] 6:20 QA

---

src/components/ResultPage/EmotionSearch.jsx
src/pages/ImgSavePage.jsx
src/pages/RecordedPage.jsx
src/pages/ResultPage.jsx
src/pages/UserInfo/KakaoDeletePage.jsx
src/pages/UserInfo/UserDeletePage.jsx

[feat] 6:32 QA

---

src/pages/Detailpage.jsx

[chore] 7: 23 QA

---

src/components/CommentBox.jsx
src/components/Reply.jsx
src/components/ResultPage/EmotionSearch.jsx
src/components/ResultPage/ResultTopbar.jsx
src/index.css
src/pages/ImgSavePage.jsx
src/pages/ResultPage.jsx

[style] 댓글 대댓글 수정 + 일본어 폰트 추가

---

.gitignore
package.json
setUpProxy.js
src/App.js
src/apis/http.js
src/apis/openLyrics.js
src/pages/TestPage.jsx

env 파일 생성해서 따로 공유 드린 API 키 입력 부탁 드려요~~!!!
<br/>
<br/>
<br/>
<br/>

Open API 위한 노력,,,

---

src/components/ImgSavePage/ImgCard.jsx
src/pages/ImgSavePage.jsx

- 이미지 자동 저장 기능 추가
<br/>
<br/>
<br/>
<br/>

[feat] 이미지 자동 저장 기능 추가

---

src/components/PostPage/PostContent.jsx

- 게시글 작성 입력창 오류 수정
<br/>
가사를 외부에서 복사 붙여넣기 했을 때 가사가 보이지 않는 이슈, 입력창 높이가 너무 늘어나는 이슈 수정했습니다.
또 60자 이상의 가사를 붙여넣기 했을 때 공백 제외 60자까지 잘라서 띄우게 수정했습니다.
<br/>
<br/>
<br/>

[fix] 게시글 작성 입력창 오류 수정

---

public/index.html
src/apis/archieve.js
src/apis/comment.js
src/apis/detail.js
src/apis/lyrics.js
src/apis/main.js
src/apis/my.js
src/apis/openLyrics.js
src/apis/search.js
src/apis/user.js
src/components/IntroTopbar.jsx
src/components/Pagination.jsx

페이지네이션 5/10 단위로 나눴습니다~
로그아웃 관련 코드도 추가했으나.... 토큰 만료시에 정상 작동하는지 파악은 하지 못했습니다....
오류를 발견하신다면 언제든 콜미.,
GA 코드도 추가했습니다!
<br/>
<br/>
<br/>
<br/>

페이지네이션 + GA 코드 추가

---

src/assets/recoil/modal.js
src/components/DetailPage/ReportPostModal.jsx
src/components/PostPage/LyricInput.jsx
src/components/PostPage/LyricSearch.jsx
src/components/PostPage/ModalTopbar.jsx
src/components/PostPage/PostInput.jsx
src/components/PostPage/PostModal.jsx
src/components/common/MainPage/FloatingBtn.jsx
src/hooks/useToggleModal.js
src/pages/Mainpage.jsx

UPLO (게시글 작성부분) 모달화 완료
<br/>
- 메인페이지 플로팅버튼 클릭 시 게시글 작성 모달 생성
- 게시글 작성 모달 내 '직접가사입력하기' 클릭 시 가사입력 모달 생성
- 게시글 작성 모달 내 '가사검색하기' 클릭 시 가사검색 모달 임시처리
<컴포넌트 정리>
게시글 작성모달 : PostModal.jsx (내부 내용: PostInput.jsx)
직접가사입력하기 : LyricInput.jsx
가사검색하기(임시) : LyricSearch.jsx
+게시글작성모달, 직접가사입력모달에 포함되는 ModalTopbar 새로 생성
<br/>
<br/>
이슈1. 모달 외부스크롤 방지 (position:absolute 시 데이터 에러발생)
원래는 배경에 position: absolute를 지정하고 모달래퍼에 overflow: auto/scroll로 지정하면 적용되어야 하는데, 데이터가 안 뜨는 오류가 발생하거나 스크롤이 허용되는 둘 중의 한 현상만 계속 발생
=> fixed/absolute와 useEffect 내 overflow 등을 계속 만지면서.. 해결
이슈2. 페이지->모달로 전환하면서 화면비율 100%가 적용되지 않음
=> 상위-하위 컴포넌트의 포지션관계 점검과 여백값에 비율 설정으로 해결
이슈3. 모달관리 변수
1 게시글작성모달 -> newPost
2 직접가사입력모달 -> lyricInputModal
그리고 가끔 (모달로직관련)변수에 예를 들면 modalState, openModal, isOpen 등에 1,2 가 붙어있다면 각각 위의 순서와 관련된 아이들이라 생각하시면 됩니다..... 로직이 동일하고 …

[feat] UPLO 모달화 완료

---

package-lock.json
package.json
public/index.html
src/App.js
src/components/CommentBox.jsx
src/components/Reply.jsx
src/index.js
src/pages/Mainpage.jsx
src/pages/MyPage.jsx
src/pages/RecommendPage.jsx
src/pages/SearchPage.jsx

<br/>
<br/>
<br/>
- 기존에 있던 헬멧 라이브러리 삭제했습니다!
<br/>

[chore] 아이폰 상단바 색상 테스트

---

src/components/common/MainPage/FloatingBtn.jsx
src/pages/Mainpage.jsx
src/pages/ResultPage.jsx

result 페이지 FloatingBtn 에러수정
<br/>
<br/>
<br/>
메인에 있던 플로팅버튼이 resultpage에서도 동일하게 작동해야했어서 났던 오류라 메인페이지 코드 그대로 추가해서 해결했습니다 !~
<br/>

[Feat] result 페이지 FloatingBtn 에러수정

---

src/components/IntroTopbar.jsx
src/components/PostPage/ModalTopbar.jsx

topbar z-index값 수정
<br/>
<br/>
<br/>
<br/>

[Feat] topbar z-index값 수정

---

src/components/PostPage/LyricInput.jsx
src/components/PostPage/PostInput.jsx
src/components/PostPage/PostModal.jsx
src/components/PostPage/SearchTrackModal.jsx
src/components/common/MainPage/FloatingBtn.jsx

[fix] 모바일 화면 상 오류 해결

---

src/components/PostPage/LyricInput.jsx
src/components/PostPage/ModalTopbar.jsx
src/components/PostPage/PostModal.jsx
src/components/PostPage/SearchContent.jsx
src/components/PostPage/SearchTrackModal.jsx

- 가사 검색에서 직접입력 모달 열리도록 이동 추가
- 게시글작성 닫기 시 내용 초기화
- 소소하게 글자색 언급해주신거 수정
<br/>
<br/>
<br/>
<br/>

[Feat] 게시글작성 로직 추가수정

---

src/components/PostPage/LyricInput.jsx
src/components/PostPage/PostInput.jsx
src/components/TopTab.jsx

가사입력 ui 추가수정
<br/>
<br/>
<br/>
<br/>

[fix] 가사입력 ui 추가수정

---

src/apis/http.js
src/apis/openLyrics.js
src/assets/recoil/apiRecoil.js
src/components/ImgSavePage/ImgSaveModal.jsx
src/components/PostPage/PostInput.jsx
src/components/PostPage/SearchContent.jsx
src/components/PostPage/SearchTrackModal.jsx
src/components/PostPage/SelectLyricModal.jsx

<br/>
<br/>
<br/>
- PostInput 컴포넌트에서 스포티파이 토큰 받아오는 API 호출하고 있습니다!
<br/>

[feat] 스포티파이 토큰 API 연결 및 일부 UI 수정

---

src/apis/openLyrics.js

[test] 스포티파이 관련 API 콘솔 추가

---

src/apis/http.js
src/apis/openLyrics.js

[fix] 가사 선택 API withCredentials 설정

---

src/apis/http.js
src/apis/openLyrics.js

[fix] 가사 선택 API withCredentials 해제

---

src/pages/Mainpage.jsx

로직 오류 재빠르게 해결해올립니다..
<br/>
<br/>
<br/>
<br/>

[hotfix] 닉네임 수정 오류 해결

---

src/apis/openLyrics.js
src/components/ImgSavePage/ImgCard.jsx
src/components/PostPage/SearchContent.jsx
src/components/PostPage/SearchTrackModal.jsx
src/components/PostPage/SelectLyricModal.jsx

[fix] 일부 UI 수정 및 검색 결과 반환 개수 수정

---

src/components/PostPage/SearchContent.jsx
src/components/PostPage/SearchTrackModal.jsx
src/components/PostPage/SelectLyricModal.jsx
src/components/PostPage/Toast.jsx

[fix] UPLO 관련 QA 반영

---

src/components/PostPage/PostModal.jsx

[test] 포스트 모달 외부 스크롤 방지

---

public/index.html
src/components/PostPage/SearchContent.jsx
src/components/PostPage/SearchTrackModal.jsx
src/index.css

[test] 입력창 클릭 시 화면 확대 방지 및 폰트 적용 테스트

---

src/components/DetailPage/GotoSong.jsx
src/components/PostPage/PostModal.jsx
src/components/PostPage/SearchContent.jsx
src/components/PostPage/SearchTrackModal.jsx
src/components/PostPage/SelectLyricModal.jsx
src/components/ResultPage/FilterResult.jsx
src/components/common/LikeLyrics.jsx
src/components/common/LyricsItem.jsx
src/components/common/MainPage/ChartSection.jsx
src/components/common/ResultLyrics.jsx
src/pages/Mainpage.jsx
src/statics/styles/GlobalStyle.js

[fix] 스크롤 오류 해결 및 수정된 UI 반영

---

src/components/RecordedPage/BookmarkedComment.jsx
src/components/ResultPage/FilterResult.jsx

검색결과 내 상단고정 (qa반영)
<br/>
<br/>
<br/>
<br/>

[style] 검색결과 내 상단고정

---

src/components/PostPage/SelectLyricModal.jsx

[fix] 로딩바 크기 수정

---

src/App.js
src/apis/user.js
src/components/PostPage/ModalTopbar.jsx
src/components/PostPage/PostInput.jsx
src/components/ResultPage/ResultTopbar.jsx
src/components/TopTab.jsx
src/components/common/EmotionList.jsx
src/components/common/MainPage/FloatingBtn.jsx
src/pages/Mainpage.jsx
src/pages/PostPage.jsx
src/pages/ResultPage.jsx
src/pages/SearchPage.jsx

[feat] 작성 페이지 변환 및 이전 경로 저장

---

src/components/CommentBox.jsx
src/components/DetailPage/LyricWithWriter.jsx
src/components/PostPage/PostInput.jsx
src/components/RecordedPage/BookmarkedComment.jsx

- 상세페이지에서 프로필 옆 '쾌감' 감정칩 0 표기현상
- 내가남긴>대댓글 경로 및 좋아요 수 표기
<br/>
<br/>
<br/>
<br/>

[fix] 감정칩 0 표기, 내가남긴>대댓글 경로 및 좋아요 수정

---

src/components/ResultPage/FilterResult.jsx

[style] 검색결과 내 상단고정 re
<br/>
<br/>
<br/>
<br/>

[style] 검색결과 내 상단고정 re

---

src/components/ResultPage/FilterResult.jsx
src/components/ResultPage/ResultTopbar.jsx
src/pages/SearchPage.jsx

- 검색결과 페이지 내 검색어: 플레이스홀더->텍스트
- 검색어 수정 즉시 변화->우측 버튼 눌러야 출력되도록 수정
- 플레이스홀더 문구 수정
<br/>
<br/>
<br/>
<br/>

[fix] 검색 결과페이지 출력관련 수정

---

src/components/ResultPage/ResultTopbar.jsx

[style] 결과페이지 상단바 스타일

---

src/apis/user.js
src/components/DetailPage/GotoSong.jsx
src/components/common/LikeLyrics.jsx
src/components/common/LyricsItem.jsx
src/components/common/ResultLyrics.jsx

가수명-곡제목 간격 수정 2px->4px (uplo 제외 모든 컴포넌트)
<br/>
<br/>
<br/>
<br/>

[style] 가수명-곡제목 간격 수정

---

src/pages/ResultPage.jsx

[fix] 결과 페이지 괄호 오류 해결

---

src/apis/http.js
src/apis/user.js
src/components/ResultPage/FilterResult.jsx
src/components/common/ResultLyrics.jsx
src/pages/Mainpage.jsx
src/pages/UserInfo/InitialPage.jsx

<br/>
- .env 파일에 baseURL 추가했습니다.
<br/>
<br/>
<br/>

[feat] baseURL 수정 및 세션 스토리지 초기화

---

src/components/RecommendPage/RecCarousel.jsx
src/components/RecommendPage/RecLyrics.jsx
src/components/RecommendPage/RecLyricsSkeleton.jsx
src/hooks/useRecInfiniteQuery.js

무한 스크롤에 나는 요상한 에러를 수정하였습니다.
쓸데없는 코드들을 제거하였습니다. (콘솔은 아직 유지)
<br/>

[fix] 무한 스크롤 에러 수정

---

src/components/Pagination.jsx
src/components/ResultPage/FilterResult.jsx
src/pages/ResultPage.jsx

[Feat] 결과페이지 UI 오류 수정

---

src/components/Pagination.jsx

[Feat] 페이지네이션 간격 수정

---

src/components/Pagination.jsx

[Feat] 페이지네이션 UI 수정

---

src/components/Pagination.jsx

[Fix] 페이지네이션 개수 및 UI 수정

---

src/components/DetailPage/LyricWithWriter.jsx
src/components/Pagination.jsx
src/components/common/EmotionChip.jsx

[Fix] 페이지네이션 오류 수정 및 감정칩 NaN 뜨는 오류 해결

---

src/components/Pagination.jsx
src/components/RecordedPage/Bookmarked.jsx
src/components/RecordedPage/BookmarkedComment.jsx
src/components/RecordedPage/BookmarkedEmotion.jsx
src/components/RecordedPage/BookmarkedLyric.jsx
src/components/RecordedPage/Saved.jsx
src/components/ResultPage/EmotionSearch.jsx
src/pages/RecordedPage.jsx

[fix] QA 반영

---

src/apis/user.js
src/components/RecordedPage/BookmarkedEmotion.jsx
src/components/ResultPage/EmotionSearch.jsx
src/pages/MyPage.jsx

[Fix] 소소한 수정

---

src/apis/main.js
src/components/RecommendPage/RecCarousel.jsx
src/components/common/MainPage/LikeSection.jsx
src/pages/UserInfo/KakaoNicknamePage.jsx
src/pages/UserInfo/LoginPage.jsx
src/pages/UserInfo/NicModifyPage.jsx
src/pages/UserInfo/PasModifyPage.jsx
src/pages/UserInfo/SignupPage.jsx
src/pages/UserInfo/UserDeletePage.jsx
src/pages/UserInfo/UserModifyIntroPage.jsx

QA 반영사항 및 점검 사항 반영하였습니다.
<br/>
<br/>
<br/>
<br/>

[Fix} 소소한 수정

---

src/components/ResultPage/FilterResult.jsx
src/components/common/MainPage/SearchSection.jsx

[Fix] 다른 방식으로 검색 로직 수정

---

src/components/ResultPage/FilterResult.jsx

[Fix] 드롭다운 오류 해결

---

src/components/ResultPage/FilterResult.jsx
src/components/common/MainPage/LikeSection.jsx
src/components/common/MainPage/SearchSection.jsx

[Fix] 드롭다운 로직 재수정

---

src/components/RecordedPage/Saved.jsx

[Fix] 저장 목록 간격 수정

---

src/components/common/MainPage/ErrorModal.jsx

[feat] 팝업 모달 클릭수정

---

src/pages/Mainpage.jsx

[Fix] 질라 api 작동으로 모달 주석처리

---

src/pages/Mainpage.jsx

[chore] 대동제 이벤트 모달 제거
